INSERT INTO case_entity (id, created_date, last_modified_date, uuid, version, case_number_number, case_number_year,  case_state, case_type, date_of_entry) VALUES (1, NOW(), NOW(), uuid_generate_v4(), 1, 2881, 22, 'DISMISSED', 'P', '2023-01-14');
INSERT INTO case_entity (id, created_date, last_modified_date, uuid, version, case_number_number, case_number_year,  case_state, case_type, date_of_entry) VALUES (2, NOW(), NOW(), uuid_generate_v4(), 1, 5076, 21, 'CLOSED', 'K', '2021-08-26');
INSERT INTO case_entity (id, created_date, last_modified_date, uuid, version, case_number_number, case_number_year,  case_state, case_type, date_of_entry) VALUES (3, NOW(), NOW(), uuid_generate_v4(), 1, 3272, 21, 'OPEN', 'W', '2022-02-13');
INSERT INTO case_entity (id, created_date, last_modified_date, uuid, version, case_number_number, case_number_year,  case_state, case_type, date_of_entry) VALUES (4, NOW(), NOW(), uuid_generate_v4(), 1, 9914, 21, 'DISMISSED', 'C', '2021-12-03');
INSERT INTO case_entity (id, created_date, last_modified_date, uuid, version, case_number_number, case_number_year,  case_state, case_type, date_of_entry) VALUES (5, NOW(), NOW(), uuid_generate_v4(), 1, 6176, 22, 'OPEN', 'W', '2022-02-04');
INSERT INTO case_entity (id, created_date, last_modified_date, uuid, version, case_number_number, case_number_year,  case_state, case_type, date_of_entry) VALUES (6, NOW(), NOW(), uuid_generate_v4(), 1, 9841, 21, 'DISMISSED', 'K', '2021-03-30');
INSERT INTO case_entity (id, created_date, last_modified_date, uuid, version, case_number_number, case_number_year,  case_state, case_type, date_of_entry) VALUES (7, NOW(), NOW(), uuid_generate_v4(), 1, 6693, 21, 'DISMISSED', 'K', '2021-09-21');
INSERT INTO case_entity (id, created_date, last_modified_date, uuid, version, case_number_number, case_number_year,  case_state, case_type, date_of_entry) VALUES (8, NOW(), NOW(), uuid_generate_v4(), 1, 7397, 21, 'DISMISSED', 'K', '2022-08-11');
INSERT INTO case_entity (id, created_date, last_modified_date, uuid, version, case_number_number, case_number_year,  case_state, case_type, date_of_entry) VALUES (9, NOW(), NOW(), uuid_generate_v4(), 1, 4892, 21, 'CLOSED', 'Co', '2021-07-24');
INSERT INTO case_entity (id, created_date, last_modified_date, uuid, version, case_number_number, case_number_year,  case_state, case_type, date_of_entry) VALUES (10, NOW(), NOW(), uuid_generate_v4(), 1, 3471, 21, 'CLOSED', 'K', '2022-07-08');

